### ISSUE TITLE
Thống kê các category

### ISSUE THREAD

**Issue by DTHNhung** [GreenZe/Essay-Wikipedia#2]
@GreenZe  Ninh sẽ phân tích và xử lý

**Comment by HeluPeter** [comment]
> @GreenZe Ninh sẽ phân tích và xử lý

Nhung giải thích rõ hơn đi ạ ^^

**Comment by DTHNhung** [comment]
- Từ file dữ liệu đếm các category, t dùng các biến count hoặc sử dụng hàm có sẵn chia số lần xuất hiện thành các khoảng

- Ví dụ:   Có ít nhất 100 lần xuất hiện >=100

- Nếu chưa nghĩ ra cách làm, thì cứ thử chia rồi phân tích tiếp

**Comment by HeluPeter** [comment]
> * Từ file dữ liệu đếm các category, t dùng các biến count hoặc sử dụng hàm có sẵn chia số lần xuất hiện thành các khoảng
> * Ví dụ:   Có ít nhất 100 lần xuất hiện >=100
> * Nếu chưa nghĩ ra cách làm, thì cứ thử chia rồi phân tích tiếp

Cái này có cần đầu vào và yêu cầu đầu ra là gì không?

**Comment by DTHNhung** [comment]
chưa cần
